[project]
name = "image-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.23"
dependencies = [
"chromedriver-autoinstaller==0.4.0",
"pyinstaller==5.9.0",
"PyQt5",
"requests==2.31.0",
"selenium==4.8.3"
]
